"""Deep Agent P1 共享领域/传输契约。"""

from .algorithm_executor import (
    AlgorithmExecutor,
    AlgorithmExecutorError,
    validate_executor_result,
)
from .algorithm_specs import (
    AlgorithmSpec,
    CausalDirectLiNGAMInput,
    CausalOlcInput,
    CausalPcInput,
    DEFAULT_ALGORITHM_SPECS,
    DIRECT_LINGAM_SPEC,
    OLC_SPEC,
    PC_SPEC,
)
from .error_codes import (
    SERVER_OUTPUT_ERROR_CODES,
    USER_INPUT_ERROR_CODES,
    SafeErrorCode,
    is_server_output_error,
    is_user_input_error,
)
from .fake_algorithm_executor import FakeAlgorithmExecutor
from .identity import (
    CAUSAL_INVOCATION_NAMESPACE,
    ResponseIdentity,
    build_invocation_id,
    build_logical_call_key,
    build_result_ref,
    canonical_mcp_context_payload,
    new_message_execution_id,
    resolve_response_identity,
)
from .models import (
    ActionAttempt,
    AlgorithmExecutionCommand,
    AlgorithmResult,
    AlgorithmResultProvenance,
    ContractModel,
    DataProfile,
    Diagnostics,
    EvidenceResult,
    FinalAnalysisDecision,
    GraphEdge,
    InvocationRecord,
    McpInvocationContext,
    RawResultMetadata,
    ReducerConflictError,
    ResultAssessment,
    RevisionProposal,
    SafeWarning,
    ScientificConflict,
    StandardizedGraph,
    WebEvidenceResult,
    build_raw_result_metadata,
    canonical_json_bytes,
    merge_action_ledger,
    merge_algorithm_results,
    merge_evidence_results,
)
from .registry import (
    AlgorithmRegistry,
    RegistryConflictError,
    RegistryEntry,
    UnknownCapabilityError,
    build_default_registry,
)

__all__ = [
    "ActionAttempt",
    "AlgorithmExecutionCommand",
    "AlgorithmExecutor",
    "AlgorithmExecutorError",
    "AlgorithmRegistry",
    "AlgorithmResult",
    "AlgorithmResultProvenance",
    "AlgorithmSpec",
    "CAUSAL_INVOCATION_NAMESPACE",
    "CausalDirectLiNGAMInput",
    "CausalOlcInput",
    "CausalPcInput",
    "ContractModel",
    "DataProfile",
    "DEFAULT_ALGORITHM_SPECS",
    "Diagnostics",
    "DIRECT_LINGAM_SPEC",
    "EvidenceResult",
    "FakeAlgorithmExecutor",
    "FinalAnalysisDecision",
    "GraphEdge",
    "InvocationRecord",
    "McpInvocationContext",
    "OLC_SPEC",
    "PC_SPEC",
    "RawResultMetadata",
    "ReducerConflictError",
    "RegistryConflictError",
    "RegistryEntry",
    "ResponseIdentity",
    "ResultAssessment",
    "RevisionProposal",
    "SERVER_OUTPUT_ERROR_CODES",
    "SafeErrorCode",
    "SafeWarning",
    "ScientificConflict",
    "StandardizedGraph",
    "USER_INPUT_ERROR_CODES",
    "UnknownCapabilityError",
    "WebEvidenceResult",
    "build_default_registry",
    "build_invocation_id",
    "build_logical_call_key",
    "build_raw_result_metadata",
    "build_result_ref",
    "canonical_json_bytes",
    "canonical_mcp_context_payload",
    "is_server_output_error",
    "is_user_input_error",
    "merge_action_ledger",
    "merge_algorithm_results",
    "merge_evidence_results",
    "new_message_execution_id",
    "resolve_response_identity",
    "validate_executor_result",
]

